#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" 
 # Get root directory of project
PROJECT_DIR=$(dirname $SCRIPTS_DIR)

if [ ! -d  $PROJECT_DIR/build ]; then
  mkdir -p $PROJECT_DIR/build;
fi

printf " \n--------------- Building Project ---------------\n\n"

cmake --build $PROJECT_DIR/build

echo
echo "-- ll $ PROJECT_DIR/bin:"
ls -l $PROJECT_DIR/bin
